### ISSUE TITLE
Namespace is Elasty

### ISSUE THREAD

**Issue by AndyCross** [azure-contrib/netmfazurestorage#1]
I'd rather not have everyone using my company's name in their project ;-)

**Comment by richorama** [comment]
Change your company name?

**Comment by AndyCross** [comment]
:-P

More of a "this isn't supported by Elastacloud so don't fekkin sue us :-P"

**Comment by richorama** [comment]
you should probably add a license as well then...

**Comment by AndyCross** [comment]
It's now Apache2
